# file: ssp/tasks/configure-common.php
#
---


- name: Configure SSP
  template:
    src: "config/config-{{ ssp_version }}.php.j2"
    dest: "{{ ssp_configdir }}/config.php"
    backup: yes
    force: yes
  become: yes
  notify:
    - restart webserver
  tags:
    - ssp:config:config




- name: Ensure SP SSL certificate is copied
  copy:
    content: '{{ item.content }}'
    dest: "{{ item.dest }}"
    owner: "{{ ssp_webuser }}"
    group: "{{ ssp_webgroup }}"
    mode: "{{ item.mode }}"
  with_items:
    - content: "{{ ssp_ssl_cert }}"
      dest: "{{ ssp_certdir }}/sp-sso.crt"
      mode: "0644"
    - content: "{{ ssp_ssl_cert_key }}"
      dest: "{{ ssp_certdir }}/sp-sso.key"
      mode: "0600"
  when: ssp_self_signed_cert_generate|bool == False
  become: yes
  no_log: yes
  tags:
    - ssp:config:authsources




- name: Create a temporary directory for certificate (local)
  local_action:
    module: tempfile
    state: directory
    suffix: certificate
  register: tmp_cert_dir
  tags:
    - ssp:config:authsources
  run_once: True
  when: ssp_self_signed_cert_generate|bool == True


- name: Generate self-signed SP certificates (local)
  local_action:
    module: command openssl req -newkey rsa:2048 -new -x509 -days 3652 -subj "/CN={{ item.ssl_certificate_cn }}" -nodes -out sp-{{ item.name }}.crt -keyout sp-{{ item.name }}.key
    args:
      chdir: "{{ tmp_cert_dir.path }}"
      creates: "{{ tmp_cert_dir.path }}/sp-{{ item.name }}.key"
  with_items: "{{ ssp_authsources_saml }}"
  when: item.generate_ssl_certificate and ssp_self_signed_cert_generate|bool == True
  run_once: True
  tags:
    - ssp:config:authsources


- name: Upload self-signed SP certificates
  copy:
    src: "{{ item }}"
    dest: "{{ ssp_certdir }}"
    force: no
  with_fileglob: "{{ tmp_cert_dir.path }}/*"
  become: yes
  when: ssp_self_signed_cert_generate|bool == True
  tags:
    - ssp:config:authsources


- name: Delete local directory with certificates (local)
  local_action:
    module: file
    path: "{{ tmp_cert_dir.path }}"
    state: absent
  run_once: True
  when: ssp_self_signed_cert_generate|bool == True
  tags:
    - ssp:config:authsources




- name: Ensure SP certificate keys are installed
  file:
    state: file
    path: "{{ ssp_certdir }}/sp-{{ item.name }}.key"
    owner: "{{ ssp_webuser }}"
    group: "{{ ssp_webgroup }}"
    mode: "0600"
  with_items: "{{ ssp_authsources_saml }}"
  become: yes
  tags:
    - ssp:config:authsources

- name: Ensure SP certificates are installed
  file:
    state: file
    path: "{{ ssp_certdir }}/sp-{{ item.name }}.crt"
    owner: "{{ ssp_webuser }}"
    group: "{{ ssp_webgroup }}"
    mode: "0644"
  with_items: "{{ ssp_authsources_saml }}"
  become: yes
  tags:
    - ssp:config:authsources

- name: Configure SSP authN sources
  template:
    src: "config/authsources-{{ ssp_version }}.php.j2"
    dest: "{{ ssp_configdir }}/authsources.php"
    backup: yes
    force: yes
  become: yes
  tags:
    - ssp:config:authsources

- name: Generate self-signed IdP certificates
  command: openssl req -newkey rsa:2048 -new -x509 -days 3652 -subj "/CN={{ item.ssl_certificate_cn }}" -nodes -out idp-{{ item.entity_id }}.crt -keyout idp-{{ item.entity_id }}.key
  args:
    chdir: "{{ ssp_certdir }}"
    creates: "{{ ssp_certdir }}/idp-{{ item.entity_id }}.key"
  with_items: "{{ ssp_idp_hosts }}"
  when: ssp_idp_saml20_enabled or ssp_idp_shib13_enabled
  become: yes
  tags:
    - ssp:config:saml20-idp-hosted
    - ssp:config:shib13-idp-hosted

- name: Ensure IdP certificate keys are installed
  file:
    state: file
    path: "{{ ssp_certdir }}/idp-{{ item.entity_id }}.key"
    owner: "{{ ssp_webuser }}"
    group: "{{ ssp_webgroup }}"
    mode: "0600"
  with_items: "{{ ssp_idp_hosts }}"
  when: ssp_idp_saml20_enabled or ssp_idp_shib13_enabled
  become: yes
  tags:
    - ssp:config:saml20-idp-hosted
    - ssp:config:shib13-idp-hosted

- name: Ensure IdP certificates are installed
  file:
    state: file
    path: "{{ ssp_certdir }}/idp-{{ item.entity_id }}.crt"
    owner: "{{ ssp_webuser }}"
    group: "{{ ssp_webgroup }}"
    mode: "0644"
  with_items: "{{ ssp_idp_hosts }}"
  when: ssp_idp_saml20_enabled or ssp_idp_shib13_enabled
  become: yes
  tags:
    - ssp:config:saml20-idp-hosted
    - ssp:config:shib13-idp-hosted

- name: Configure SSP hosted SAML 2.0 IdP metadata
  template:
    src: "metadata/saml20-idp-hosted-{{ ssp_version }}.php.j2"
    dest: "{{ ssp_metadatadir }}/saml20-idp-hosted.php"
    backup: yes
    force: yes
  when: ssp_idp_saml20_enabled
  become: yes
  tags:
    - ssp:config:saml20-idp-hosted

- name: Configure SSP hosted SAML 1.1 IdP metadata
  template:
    src: "metadata/shib13-idp-hosted-{{ ssp_version }}.php.j2"
    dest: "{{ ssp_metadatadir }}/shib13-idp-hosted.php"
    backup: yes
    force: yes
  when: ssp_idp_shib13_enabled
  become: yes
  tags:
    - ssp:config:shib13-idp-hosted

- name: Enable required SSP modules
  command: touch "{{ ssp_path }}/modules/{{ item }}/enable"
  args:
    creates: "{{ ssp_path }}/modules/{{ item }}/enable"
  with_items: "{{ ssp_mods_enabled }}"
  become: yes
  tags:
    - ssp:config:mods

- name: Disable unnecessary SSP modules
  command: touch "{{ ssp_path }}/modules/{{ item }}/disable"
  args:
    creates: "{{ ssp_path }}/modules/{{ item }}/disable"
  with_items: "{{ ssp_mods_disabled }}"
  become: yes
  tags:
    - ssp:config:mods

- name: Ensure required SSP metarefresh module dirs exist
  file: path={{ ssp_metadatadir }}/{{ item.output_dir }} state=directory owner={{ssp_webuser }} group={{ ssp_webgroup }}
  with_items: "{{ ssp_mod_metarefresh_sets }}"
  when: "'metarefresh' in ssp_mods_enabled"
  become: yes
  tags:
    - ssp:config:mods
    - ssp:config:mods:metarefresh

- name: Configure SSP metarefresh module
  template:
    src: "config/config-metarefresh-{{ ssp_version }}.php.j2"
    dest: "{{ ssp_configdir }}/config-metarefresh.php"
    backup: yes
    force: yes
  when: "'metarefresh' in ssp_mods_enabled"
  register: ssp_mod_metarefresh_config
  become: yes
  tags:
    - ssp:config:mods
    - ssp:config:mods:metarefresh

- name: Configure SSP cron module
  template:
    src: config/module_cron.php.j2
    dest: "{{ ssp_configdir }}/module_cron.php"
    backup: yes
    force: yes
  when: "'cron' in ssp_mods_enabled"
  become: yes
  tags:
    - ssp:config:mods
    - ssp:config:mods:cron
    - ssp:config:mods:metarefresh

- name: Configure SSP cron jobs
  cron:
    name: "{{ item.name }}"
    user: "{{ item.user | default('root') }}"
    cron_file: "{{ item.file }}"
    # Set maximum time to 300 seconds for preventing curl job from hanging
    job: "curl -k --silent -m 300 \"{{ ssp_mod_cron_url }}?key={{ ssp_mod_cron_secret }}&tag={{ item.tag }}\""
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
  with_items: "{{ ssp_mod_cron_entries }}"
  when: "'cron' in ssp_mods_enabled"
  become: yes
  tags:
    - ssp:config:mods
    - ssp:config:mods:cron
    - ssp:config:mods:metarefresh

- name: Configure SSP cron job variables
  cronvar:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    cron_file: "{{ item.file }}"
  with_items: "{{ ssp_mod_cron_vars }}"
  when: "'cron' in ssp_mods_enabled"
  become: yes
  tags:
    - ssp:config:mods
    - ssp:config:mods:cron
    - ssp:config:mods:metarefresh

#TODO- name: Refresh SSP remote SAML metadata
#  shell: "curl -k --silent \"https://localhost/{{ ssp_baseurlpath }}/module.php/cron/cron.php?key={{ ssp_mod_cron_secret }}&tag={{ item }}\" > /dev/null 2>&1"
#  with_items:
#    - hourly
#    - daily
#  when: "ssp_mod_metarefresh_config | changed"
#  become: yes

- name: Configure SSP discopower module
  template:
    src: config/module_discopower.php.j2
    dest: "{{ ssp_configdir }}/module_discopower.php"
    backup: yes
    force: yes
  when: "'discopower' in ssp_mods_enabled"
  become: yes
  tags:
    - ssp:config:mods
    - ssp:config:mods:discopower

- name: Update SSP discopower module dictionary definitions
  template:
    src: modules/discopower/dictionaries/tabs.definition.json.j2
    dest: "{{ ssp_path }}/modules/discopower/dictionaries/tabs.definition.json"
    backup: yes
    force: yes
  when: "'discopower' in ssp_mods_enabled and ssp_mod_discopower_dictionaries is defined"
  become: yes
  tags:
    - ssp:config:mods
    - ssp:config:mods:discopower
